export const popular = [
  { from: "Colombo", to: "New York" },
  { from: "Tokyo", to: "Paris" },
  { from: "Tokyo", to: "New York" },
  { from: "Sydney", to: "San Francisco" },
  { from: "Berlin", to: "Chicago" },
  { from: "Mumbai", to: "Toronto" },
  { from: "Hong Kong", to: "Los Angeles" },
  { from: "Cairo", to: "London" },
  { from: "New York", to: "London" },
  { from: "San Francisco", to: "Paris" },
  { from: "New York", to: "Mumbai" },
  { from: "New York", to: "Tokyo" },
  { from: "Chicago", to: "Berlin" },
  { from: "Tokyo", to: "Sydney" },
  { from: "Mumbai", to: "Singapore" },
  { from: "Mumbai", to: "London" },
  { from: "Beijing", to: "Dubai" },
  { from: "Rome", to: "Houston" },
  { from: "Auckland", to: "Los Angeles" },  
  { from: "Jeju", to: "Seoul" },
  { from: "Melbourne", to: "Sydney" },
  { from: "Rio de Janeiro", to: "Auckland" },
  { from: "Fukuoka", to: "Tokyo" },
  { from: "Chicago", to: "New York" },
  { from: "Hanoi", to: "Ho Chi Minh City" },
  { from: "Dublin", to: "London" },
  { from: "Amsterdam", to: "London" },
  { from: "Antalya", to: "Istanbul" },
  { from: "Edinburgh", to: "London" },
  { from: "Istanbul", to: "Moscow" },
  { from: "Istanbul", to: "Dubai" },
  { from: "Vancouver", to: "Victoria" },
  { from: "Jeddah", to: "Cairo" },
  { from: "New Delhi", to: "Heathrow" },
  { from: "Los Angeles", to: "Chicago" },
  { from: "Toronto", to: "Montreal" },
  { from: "Mexico City", to: "Bogota" },
  { from: "Bangkok", "to": "Singapore" },
  { from: "Jakarta", to: "Kuala Lumpur" },
  { from: "Seoul", to: "Beijing" },
  { from: "Hong Kong", to: "Shanghai" },
  { from: "Tokyo", to: "Osaka" },
  { from: "Sydney", to: "Auckland" },
  { from: "Honolulu", to: "Los Angeles" },
  { from: "Anchorage", to: "Denver" },
  { from: "Phoenix", to: "Denver" },
  { from: "Bogota", to: "Lima" },
  { from: "Caracas", to: "Bogota" },
  { from: "Tehran", to: "Dubai" },
  { from: "Baghdad", to: "Istanbul" },
  { from: "Jerusalem", to: "London" },
  { from: "Kathmandu", to: "Delhi" },
  { from: "Manila", to: "Hong Kong" },
  { from: "Hanoi", to: "Beijing" },
  { from: "Lisbon", to: "Madrid" },
  { from: "Barcelona", to: "Paris" },
  { from: "Athens", to: "Rome" },
  { from: "Cancún", to: "Miami" },
  { from: "Vancouver", to: "Los Angeles" },
  { from: "Las Vegas", to: "New York" },
  { from: "Miami", to: "New York" },
  { from: "Washington D.C.", to: "London" },
  { from: "San Francisco", to: "Tokyo" },
  { from: "Detroit", to: "Toronto" },
  { from: "Atlanta", to: "London" },
  { from: "Dallas", to: "Mexico City" },
  { from: "Lima", to: "Santiago" },
  { from: "Buenos Aires", to: "London" },
  { from: "Cape Town", to: "London" },
  { from: "Copenhagen", to: "Berlin" },
  { from: "Stockholm", to: "London" },
  { from: "Zurich", to: "New York" },
  { from: "Munich", to: "Dubai" },
  { from: "Frankfurt", to: "New York" },
  { from: "Vienna", to: "London" },
  { from: "Budapest", to: "Paris" },
  { from: "Warsaw", to: "Berlin" },
  { from: "Moscow", to: "London" },
  { from: "Dubai", to: "Sydney" },
  { from: "Abu Dhabi", to: "London" },
  { from: "Doha", to: "London" },
  { from: "Singapore", to: "London" },
  { from: "Seoul", to: "Los Angeles" },
  { from: "Shanghai", to: "Sydney" },
  { from: "Beijing", to: "New York" },
  { from: "Delhi", to: "London" },
  { from: "Mumbai", to: "Dubai" },
  { from: "Kolkata", to: "Dubai" },
  { from: "Bangkok", to: "London" },
  { from: "Jakarta", to: "Sydney" },
  { from: "Manila", to: "San Francisco" },
  { from: "Hong Kong", to: "Dubai" },
  { from: "Tokyo", to: "Los Angeles" },
  { from: "Sydney", to: "London" },
  { from: "Auckland", to: "Los Angeles" },
  { from: "Melbourne", to: "Dubai" },
  { from: "Cape Town", to: "Dubai" },
  { from: "Nairobi", to: "Dubai" },
  { from: "Boston", to: "London" },
  { from: "Montreal", to: "Paris" },
  { from: "Toronto", to: "Berlin" },
  { from: "Washington D.C.", to: "Paris" },
  { from: "Miami", to: "London" },
  { from: "Houston", to: "London" },
  { from: "Chicago", to: "Paris" },
  { from: "Denver", to: "London" },
  { from: "Seattle", to: "London" },
  { from: "Atlanta", to: "Frankfurt" },
  { from: "Philadelphia", to: "Rome" },
  { from: "Dallas", to: "Madrid" },
  { from: "Orlando", to: "Dublin" },
  { from: "Phoenix", to: "Amsterdam" },
  { from: "San Francisco", to: "Seoul" },
  { from: "Los Angeles", to: "Manila" },
  { from: "New York", to: "Shanghai" },
  { from: "Chicago", to: "Beijing" },
  { from: "Toronto", to: "Hong Kong" },
  { from: "Vancouver", to: "Tokyo" },
  { from: "Honolulu", to: "Tokyo" },
  { from: "Atlanta", to: "Seoul" },
  { from: "Dallas", to: "Sydney" },
  { from: "Houston", to: "Singapore" },
  { from: "Miami", to: "Dubai" },
  { from: "Seattle", to: "Hong Kong" },
  { from: "Denver", to: "Tokyo" },
  { from: "Phoenix", to: "Beijing" },
  { from: "Las Vegas", to: "Tokyo" },
  { from: "Paris", to: "Singapore" },
  { from: "Berlin", to: "Tokyo" },
  { from: "Rome", to: "Mumbai" },
  { from: "Madrid", to: "Beijing" },
  { from: "Amsterdam", to: "Tokyo" },
  { from: "Frankfurt", to: "Singapore" },
  { from: "Zurich", to: "Hong Kong" },
  { from: "Copenhagen", to: "Seoul" },
  { from: "Stockholm", to: "Shanghai" },
  { from: "Oslo", to: "Delhi" },
  { from: "Vienna", to: "Bangkok" },
  { from: "Brussels", to: "Kuala Lumpur" },
  { from: "Warsaw", to: "Seoul" },
  { from: "Budapest", to: "Tokyo" },
  { from: "Prague", to: "Singapore" },
  { from: "Mumbai", to: "Singapore" },
  { from: "Delhi", to: "Hong Kong" },
  { from: "Bangkok", to: "Tokyo" },
  { from: "Jakarta", to: "Hong Kong" },
  { from: "Manila", to: "Tokyo" },
  { from: "Ho Chi Minh City", to: "Singapore" },
  { from: "Taipei", to: "Singapore" },
  { from: "Seoul", to: "Bangkok" },
  { from: "Shanghai", to: "Tokyo" },
  { from: "Beijing", to: "Singapore" },
  { from: "Perth", to: "Tokyo" },
  { from: "Brisbane", to: "Singapore" },
  { from: "Adelaide", to: "Tokyo" },
  { from: "Wellington", to: "Melbourne" },
  { from: "Chennai", to: "Kuala Lumpur" },
  { from: "Bengaluru", to: "Singapore" },
  { from: "Osaka", to: "Shanghai" },
  { from: "Nagoya", to: "Seoul" },
  { from: "New Delhi", to: "Riyadh" },
  { from: "Islamabad", to: "Dubai" },
  { from: "Dhaka", to: "Singapore" },
  { from: "Yangon", to: "Bangkok" },
  { from: "Phuket", to: "Singapore" },
  { from: "Cebu", to: "Hong Kong" },
  { from: "New York", to: "San Francisco" },
  { from: "Chicago", to: "Houston" },
  { from: "Los Angeles", to: "Miami" },
  { from: "Toronto", to: "Vancouver" },
  { from: "Mexico City", to: "Los Angeles" },
  { from: "Rio de Janeiro", to: "Santiago" },
  { from: "Bogota", to: "Panama City" },
  { from: "Lima", to: "Mexico City" },
  { from: "Santiago", to: "Buenos Aires" },
  { from: "Atlanta", to: "Los Angeles" },
  { from: "Denver", to: "Seattle" },
  { from: "Las Vegas", to: "Seattle" },
  { from: "Boston", to: "Miami" },
  { from: "Riyadh", to: "London" },
  { from: "Doha", to: "New York" },
  { from: "Tel Aviv", to: "London" },
  { from: "Istanbul", to: "Berlin" },
  { from: "Johannesburg", to: "London" },
  { from: "Nairobi", to: "London" },
  { from: "Accra", to: "London" },
  { from: "Lagos", to: "London" },
  { from: "Cairo", to: "New York" },
  { from: "Casablanca", to: "Paris" },
  { from: "Addis Ababa", to: "Dubai" },
  { from: "Durban", to: "London" },
  { from: "Kuwait City", to: "London" },
  { from: "Beirut", to: "Paris" },
  { from: "Algiers", to: "Paris" }
];