// src/lib/zoneAliases.js
export const zoneAliases = {
  "beijing": "Asia/Shanghai",
  "shanghai": "Asia/Shanghai",
  "tokyo": "Asia/Tokyo",
  "delhi": "Asia/Kolkata",
  "mumbai": "Asia/Kolkata",
  "moscow": "Europe/Moscow",
  "cairo": "Africa/Cairo",
  "sao paulo": "America/Sao_Paulo",
  "mexico city": "America/Mexico_City",
  "new york": "America/New_York",
  "los angeles": "America/Los_Angeles",
  "chicago": "America/Chicago",
  "houston": "America/Chicago",
  "miami": "America/New_York",
  "london": "Europe/London",
  "paris": "Europe/Paris",
  "berlin": "Europe/Berlin",
  "rome": "Europe/Rome",
  "toronto": "America/Toronto",
  "vancouver": "America/Vancouver",
  "sydney": "Australia/Sydney",
  "melbourne": "Australia/Melbourne",
  "bangkok": "Asia/Bangkok",
  "jakarta": "Asia/Jakarta",
  "seoul": "Asia/Seoul",
  "singapore": "Asia/Singapore",
  "hong kong": "Asia/Hong_Kong",
  "taipei": "Asia/Taipei",
  "istanbul": "Europe/Istanbul",
  "kinshasa": "Africa/Kinshasa",
  "florida": "America/New_York"
};
