export const zoneAliases = {
  "new york": "America/New_York",
  "london": "Europe/London",
  "tokyo": "Asia/Tokyo",
  "nagoya": "Asia/Tokyo",
  "delhi": "Asia/Kolkata",
  "mumbai": "Asia/Kolkata",
  "sydney": "Australia/Sydney",
  "san francisco": "America/Los_Angeles",
  "berlin": "Europe/Berlin",
  "paris": "Europe/Paris",
  "singapore": "Asia/Singapore",
  "dubai": "Asia/Dubai",
  "seoul": "Asia/Seoul",
  "los angeles": "America/Los_Angeles",
  "toronto": "America/Toronto",
  "moscow": "Europe/Moscow",
  "beijing": "Asia/Shanghai",
  "chicago": "America/Chicago",
  "bangkok": "Asia/Bangkok",
  "jakarta": "Asia/Jakarta",
  "melbourne": "Australia/Melbourne",
  "hong kong": "Asia/Hong_Kong",
  "rome": "Europe/Rome",
  "madrid": "Europe/Madrid",
  "amsterdam": "Europe/Amsterdam",
  "cairo": "Africa/Cairo",
  "vancouver": "America/Vancouver",
  "boston": "America/New_York",
  "washington": "America/New_York",
  "miami": "America/New_York",
  "istanbul": "Europe/Istanbul",
  "doha": "Asia/Qatar",
  "riyadh": "Asia/Riyadh",
  "colombo": "Asia/Colombo",
  "kuala lumpur": "Asia/Kuala_Lumpur",
  "islamabad": "Asia/Karachi",
  "barcelona": "Europe/Madrid",
  "abu dhabi": "Asia/Dubai",
  "accra": "Africa/Accra",
  "addis ababa": "Africa/Addis_Ababa",
  "adelaide": "Australia/Adelaide",
  "algiers": "Africa/Algiers",
  "almaty": "Asia/Almaty",
  "anchorage": "America/Anchorage",
  "anuradhapura": "Asia/Colombo",
  "antalya": "Europe/Istanbul",
  "austin": "America/Chicago",
  "badulla": "Asia/Colombo",
  "baghdad": "Asia/Baghdad",
  "bangalore": "Asia/Kolkata",
  "chennai": "Asia/Kolkata",
  "belgrade": "Europe/Belgrade",
  "bogota": "America/Bogota",
  "brisbane": "Australia/Brisbane",
  "brussels": "Europe/Brussels",
  "budapest": "Europe/Budapest",
  "buenos aires": "America/Argentina/Buenos_Aires",
  "busan": "Asia/Seoul",
  "cancún": "America/Cancun",
  "cape town": "Africa/Johannesburg",
  "caracas": "America/Caracas",
  "casablanca": "Africa/Casablanca",
  "copenhagen": "Europe/Copenhagen",
  "dallas": "America/Chicago",
  "dar es salaam": "Africa/Dar_es_Salaam",
  "denpasar": "Asia/Makassar",
  "denver": "America/Denver",
  "detroit": "America/Detroit",
  "dhaka": "Asia/Dhaka",
  "dublin": "Europe/Dublin",
  "edinburgh": "Europe/London",
  "florida": "America/New_York",
  "frankfurt": "Europe/Berlin",
  "fukuoka": "Asia/Tokyo",
  "galle": "Asia/Colombo",
  "guadalajara": "America/Mexico_City",
  "hanoi": "Asia/Ho_Chi_Minh",
  "harare": "Africa/Harare",
  "heathrow": "Europe/London",
  "helsinki": "Europe/Helsinki",
  "ho chi minh": "Asia/Ho_Chi_Minh",
  "ho chi minh city": "Asia/Ho_Chi_Minh",
  "honolulu": "Pacific/Honolulu",
  "houston": "America/Chicago",
  "hyderabad": "Asia/Kolkata",
  "jaffna": "Asia/Colombo",
  "jeddah": "Asia/Riyadh",
  "jeju": "Asia/Seoul",
  "jerusalem": "Asia/Jerusalem",
  "kandy": "Asia/Colombo",
  "kampala": "Africa/Kampala",
  "karachi": "Asia/Karachi",
  "kathmandu": "Asia/Kathmandu",
  "kingston": "America/Jamaica",
  "kolkata": "Asia/Kolkata",
  "lagos": "Africa/Lagos",
  "lahore": "Asia/Karachi",
  "las vegas": "America/Los_Angeles",
  "lima": "America/Lima",
  "lisbon": "Europe/Lisbon",
  "liverpool": "Europe/London",
  "luanda": "Africa/Luanda",
  "macau": "Asia/Macau",
  "manila": "Asia/Manila",
  "mexicali": "America/Tijuana",
  "mexico city": "America/Mexico_City",
  "minneapolis": "America/Chicago",
  "montevideo": "America/Montevideo",
  "montreal": "America/Toronto",
  "munich": "Europe/Berlin",
  "nairobi": "Africa/Nairobi",
  "new delhi": "Asia/Kolkata",
  "newark": "America/New_York",
  "athens": "Europe/Athens",
  "orlando": "America/New_York",
  "osaka": "Asia/Tokyo",
  "oslo": "Europe/Oslo",
  "panama city": "America/Panama",
  "perth": "Australia/Perth",
  "philadelphia": "America/New_York",
  "phoenix": "America/Phoenix",
  "porto alegre": "America/Sao_Paulo",
  "prague": "Europe/Prague",
  "tehran": "Asia/Tehran",
  "quito": "America/Guayaquil",
  "recife": "America/Recife",
  "warsaw": "Europe/Warsaw",
  "rio de janeiro": "America/Sao_Paulo",
  "san diego": "America/Los_Angeles",
  "shanghai": "Asia/Shanghai",
  "san jose": "America/Costa_Rica",
  "sao paulo": "America/Sao_Paulo",
  "sapporo": "Asia/Tokyo",
  "seattle": "America/Los_Angeles",
  "sofia": "Europe/Sofia",
  "stockholm": "Europe/Stockholm",
  "vienna": "Europe/Vienna",
  "victoria": "America/Vancouver",
  "washington d.c.": "America/New_York",
  "wellington": "Pacific/Auckland",
  "auckland": "Pacific/Auckland",
  "taipei": "Asia/Taipei",
  "tijuana": "America/Tijuana",
  "reykjavik": "Atlantic/Reykjavik",
  "yangon": "Asia/Yangon",
  "zurich": "Europe/Zurich",
  "pune": "Asia/Kolkata",
  "shenzhen/guangzhou": "Asia/Shanghai",
  "atlanta": "America/New_York",
  "bengaluru": "Asia/Kolkata",
  "cebu": "Asia/Manila",
  "phuket": "Asia/Bangkok",
  "santiago": "America/Santiago",
  "tel aviv": "Asia/Jerusalem",
  "durban": "Africa/Johannesburg",
  "johannesburg": "Africa/Johannesburg",
  "kuwait city": "Asia/Kuwait",
  "beirut": "Asia/Beirut"
};